name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-test-${{ hashFiles('**/Cargo.lock') }}

    - name: Run Clippy ✅
      run: cargo clippy --all-targets --all-features

    - name: Run Check ✅
      run: cargo check --all-targets --all-features

    # NOTE: Test are using actual package manages, so we have to install them
    # make - pre-installed
    # npm - TBD
    # poetry
    - run: |
        pip install poetry

    - name: Run tests ✅
      run: cargo test --verbose


  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: 
        - ubuntu-latest
        # - macos-latest
        # - windows-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ matrix.os }}-cargo-build-${{ hashFiles('**/Cargo.lock') }}

    - name: Build ✨
      run: cargo build --release

    - uses: actions/upload-artifact@v3
      with:
        name: ${{ github.event.repository.name }}-${{ matrix.os }}
        path: target/release/${{ github.event.repository.name }}${{ matrix.os == 'windows-latest' && '.exe' || '' }}
